name: Release from tag

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish release
        id: publish-release
        uses: ghalactic/github-release-from-tag@v5
        with:
          prerelease: 'false'
          reactions: heart,rocket,eyes
